version: '3.8'

services:

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

    networks:
      node_net:
        ipv4_address: 172.28.1.4

# networking for the Redis container
networks:
  node_net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16