# Generated by Django 3.2 on 2022-01-21 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('item_url', models.URLField()),
                ('target', models.CharField(choices=[('b', '_blank'), ('s', '_self')], default='s', help_text='Target url', max_length=1)),
                ('position', models.CharField(choices=[('h', 'header'), ('f', 'footer')], help_text='Position object (header or footer)', max_length=1)),
                ('show_item', models.BooleanField(default=False, verbose_name='show')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
