# Generated by Django 3.2 on 2022-01-21 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='item_url',
            field=models.CharField(max_length=2048),
        ),
    ]
