# Generated by Django 3.2 on 2022-02-06 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='target',
            field=models.CharField(choices=[('_blank', 'blank'), ('_self', 'self')], default='_self', help_text='Target url', max_length=6),
        ),
    ]
