# Generated by Django 3.2 on 2022-02-06 22:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_menu_target'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='item_url',
            field=models.CharField(help_text='Enter link address', max_length=2048, unique=True, validators=[django.core.validators.RegexValidator(message='If the link is internal it should look like this: "blog/article/", for external links it should look like this: "https://www.site.com/"', regex='^((http(s)?:\\/\\/)?([\\w-]+\\.?)+[\\w-]+[.com]*([\\w\\-\\.,@?^=%&amp;:/~\\+#]*[\\w\\-\\@?^=%&amp;/~\\+#])?)')]),
        ),
    ]
