# Generated by Django 3.2 on 2022-02-10 11:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_alter_menu_item_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ['dd_order', 'created'], 'verbose_name': 'Menu item', 'verbose_name_plural': 'Menu items'},
        ),
        migrations.AlterField(
            model_name='menu',
            name='item_url',
            field=models.CharField(help_text='Enter link address', max_length=2048, unique=True, validators=[django.core.validators.RegexValidator(message='If the link is internal it should look like this: "blog/article/", for external links it should look like this: "https://www.site.com/"', regex='^((http(s)?:\\/\\/)?([\\w-]+\\.?)+[\\w-]+[.com]*([\\w\\-\\.,@?^=%&amp;:/~\\+#]*[\\w\\-\\@?^=%&amp;/~\\+#])?)')], verbose_name='url address'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='position',
            field=models.CharField(choices=[('h', 'header'), ('f', 'footer')], help_text='Position object (header or footer)', max_length=1, verbose_name='position'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='show_item',
            field=models.BooleanField(default=False, help_text='show or hidden url address', verbose_name='show'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='target',
            field=models.CharField(choices=[('_blank', 'blank'), ('_self', 'self')], default='_self', help_text='Target url', max_length=6, verbose_name='target'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='title',
            field=models.CharField(max_length=100, unique=True, verbose_name='title'),
        ),
    ]
