# Generated by Django 3.2 on 2022-02-11 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_auto_20220210_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='title_ru',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='menu',
            name='title_uk',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='title'),
        ),
    ]
