# Generated by Django 3.2 on 2022-01-31 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='score',
            field=models.DecimalField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], decimal_places=0, max_digits=1, null=True),
        ),
    ]
