# Generated by Django 3.2 on 2022-01-31 17:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_auto_20220130_1341'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('interaction', '0002_alter_score_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.article'),
        ),
        migrations.AlterField(
            model_name='score',
            name='author',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
