# Generated by Django 3.2 on 2022-02-03 10:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_alter_imagearticle_img_alt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('interaction', '0006_favoritesarticle'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='CommentArticle',
        ),
    ]
