# Generated by Django 3.2 on 2022-02-03 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0007_rename_comment_commentarticle'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentarticle',
            name='score',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='interaction.score'),
        ),
    ]
