# Generated by Django 3.2 on 2022-02-03 19:27

import ckeditor.fields
import django.core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0008_commentarticle_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentarticle',
            name='message',
            field=ckeditor.fields.RichTextField(validators=[django.core.validators.MinLengthValidator(3)]),
        ),
    ]
