# Generated by Django 3.2 on 2022-02-03 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0009_alter_commentarticle_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='score',
            field=models.DecimalField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], decimal_places=0, default=1, max_digits=1, null=True),
        ),
    ]
