# Generated by Django 3.2 on 2022-02-03 20:08

import ckeditor.fields
import django.core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0011_alter_score_score'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentarticle',
            options={'ordering': ['article', '-created'], 'verbose_name': 'комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
        migrations.AlterField(
            model_name='commentarticle',
            name='message',
            field=ckeditor.fields.RichTextField(validators=[django.core.validators.MinLengthValidator(3)], verbose_name='комментарий'),
        ),
    ]
