# Generated by Django 3.2 on 2022-02-03 20:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subscription',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
