# Generated by Django 3.2 on 2022-02-10 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='img_alt_ru',
            field=models.CharField(blank=True, help_text='text to be loaded in case of image loss', max_length=200, null=True, verbose_name='image alternative'),
        ),
        migrations.AddField(
            model_name='user',
            name='img_alt_uk',
            field=models.CharField(blank=True, help_text='text to be loaded in case of image loss', max_length=200, null=True, verbose_name='image alternative'),
        ),
    ]
