# Generated by Django 3.2 on 2022-01-27 09:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20220127_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(help_text='used to generate URL', max_length=150, unique=True, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
    ]
