# Generated by Django 3.2 on 2022-01-27 13:40

import ckeditor.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import shared.mixins.model_utils


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0009_alter_category_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('dd_order', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(max_length=200, unique=True, validators=[django.core.validators.MinLengthValidator(3)])),
                ('slug', models.SlugField(blank=True, help_text='used to generate URL', null=True, unique=True)),
                ('article_preview', models.ImageField(help_text='article preview', upload_to='article_preview/%Y/%m/%d')),
                ('short_description', models.TextField()),
                ('content', ckeditor.fields.RichTextField()),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.category')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, shared.mixins.model_utils.ImageNameMixins),
        ),
    ]
