# Generated by Django 3.2 on 2022-01-27 13:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='img_alt',
            field=models.CharField(default=django.utils.timezone.now, help_text='текст, который будет загружен в случае потери изображения', max_length=200),
            preserve_default=False,
        ),
    ]
