# Generated by Django 3.2 on 2022-01-27 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_article_img_alt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='img_alt',
            field=models.CharField(blank=True, help_text='текст, который будет загружен в случае потери изображения', max_length=200, null=True),
        ),
    ]
