# Generated by Django 3.2 on 2022-01-27 16:02

from django.db import migrations, models
import django.db.models.deletion
import shared.mixins.model_utils


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_article_img_alt'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['dd_order', '-created'], 'verbose_name': 'article', 'verbose_name_plural': 'Articles'},
        ),
        migrations.CreateModel(
            name='ImageArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('dd_order', models.PositiveIntegerField(default=0)),
                ('image_article', models.ImageField(help_text='image article', upload_to='image_article/%Y/%m/%d')),
                ('img_alt', models.CharField(help_text='текст, который будет загружен в случае потери изображения', max_length=200)),
                ('article', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.article')),
            ],
            options={
                'verbose_name': 'article',
                'verbose_name_plural': 'Articles',
                'ordering': ['dd_order', 'created'],
            },
            bases=(models.Model, shared.mixins.model_utils.ImageNameMixins),
        ),
    ]
