# Generated by Django 3.2 on 2022-01-27 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20220127_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagearticle',
            name='image_article',
            field=models.FileField(help_text='image article', upload_to='image_article/%Y/%m/%d'),
        ),
    ]
