# Generated by Django 3.2 on 2022-01-27 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_alter_imagearticle_image_article'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagearticle',
            options={'ordering': ['dd_order', 'created'], 'verbose_name': 'image', 'verbose_name_plural': 'Images of article'},
        ),
        migrations.AlterField(
            model_name='imagearticle',
            name='image_article',
            field=models.ImageField(help_text='image article', upload_to='image_article/%Y/%m/%d'),
        ),
    ]
