# Generated by Django 3.2 on 2022-01-27 22:13

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20220127_2316'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='textpage',
            options={'ordering': ['-created'], 'verbose_name': 'text page', 'verbose_name_plural': 'Text pages'},
        ),
        migrations.AddField(
            model_name='textpage',
            name='content',
            field=ckeditor.fields.RichTextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='textpage',
            name='slug',
            field=models.SlugField(blank=True, help_text='used to generate URL', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='textpage',
            name='published',
            field=models.CharField(choices=[('d', 'draft'), ('p', 'published')], help_text='Published or draft', max_length=1),
        ),
    ]
