# Generated by Django 3.2 on 2022-01-30 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_auto_20220129_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='number_of_likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='article',
            name='number_of_reviews',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
