# Generated by Django 3.2 on 2022-01-31 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_auto_20220130_1341'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendedArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('dd_order', models.PositiveIntegerField(default=0)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.article')),
            ],
            options={
                'verbose_name': 'рекомендованная статья',
                'verbose_name_plural': 'Рекомендованные статьи',
                'ordering': ['dd_order', 'created'],
            },
        ),
    ]
