# Generated by Django 3.2 on 2022-01-31 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_recommendedarticle'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='recommended',
            field=models.ManyToManyField(to='blog.Article'),
        ),
        migrations.DeleteModel(
            name='RecommendedArticle',
        ),
    ]
