# Generated by Django 3.2 on 2022-02-03 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_alter_imagearticle_img_alt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='number_of_reviews',
        ),
    ]
