# Generated by Django 3.2 on 2022-02-05 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_remove_article_number_of_reviews'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagearticle',
            options={'ordering': ['dd_order', 'created'], 'verbose_name': 'изображение', 'verbose_name_plural': 'Изображения для статьи'},
        ),
        migrations.AlterField(
            model_name='textpage',
            name='published',
            field=models.CharField(choices=[('d', 'draft'), ('p', 'published')], default='p', help_text='Published or draft', max_length=1),
        ),
    ]
