# Generated by Django 3.2 on 2022-02-06 12:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_auto_20220205_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(blank=True, default=django.utils.timezone.now, help_text='used to generate URL', unique=True),
            preserve_default=False,
        ),
    ]
