# Generated by Django 3.2 on 2022-02-06 13:18

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_alter_article_article_preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='содержание статьи'),
        ),
        migrations.AlterField(
            model_name='article',
            name='recommended',
            field=models.ManyToManyField(help_text='не больше двух', limit_choices_to=2, to='blog.Article', verbose_name='рекомендованные статьи'),
        ),
        migrations.AlterField(
            model_name='article',
            name='short_description',
            field=models.CharField(max_length=350, verbose_name='короткое описание'),
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(blank=True, help_text='used to generate URL', null=True, unique=True),
        ),
    ]
