# Generated by Django 3.2 on 2022-02-06 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0029_alter_article_recommended'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='short_description',
            field=models.CharField(max_length=350, verbose_name='описание статьи'),
        ),
    ]
