# Generated by Django 3.2 on 2022-02-10 11:32

import ckeditor.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0030_alter_article_short_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagearticle',
            options={'ordering': ['dd_order', 'created'], 'verbose_name': 'image', 'verbose_name_plural': 'Images for article'},
        ),
        migrations.AlterField(
            model_name='article',
            name='article_preview',
            field=models.ImageField(help_text='article preview image', upload_to='article_preview/%Y/%m/%d', verbose_name='article_preview'),
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(help_text='author of article', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='author'),
        ),
        migrations.AlterField(
            model_name='article',
            name='average_rating',
            field=models.DecimalField(decimal_places=1, default=0, help_text='average article rating', max_digits=2, verbose_name='average rating'),
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(help_text='category of article', null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.category', verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=ckeditor.fields.RichTextField(help_text='the content of the article', verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='article',
            name='img_alt',
            field=models.CharField(blank=True, help_text='text to be loaded in case of image loss', max_length=200, null=True, verbose_name='image alternative'),
        ),
        migrations.AlterField(
            model_name='article',
            name='number_of_likes',
            field=models.PositiveIntegerField(default=0, help_text='number of article ratings', verbose_name='number_of_likes'),
        ),
        migrations.AlterField(
            model_name='article',
            name='recommended',
            field=models.ManyToManyField(help_text='recommended articles', to='blog.Article', verbose_name='recommended'),
        ),
        migrations.AlterField(
            model_name='article',
            name='short_description',
            field=models.CharField(help_text='a short description about the article', max_length=350, verbose_name='short description'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(help_text='title of article', max_length=200, unique=True, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='category name', max_length=100, unique=True, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='imagearticle',
            name='article',
            field=models.ForeignKey(help_text='linked Article model with image', null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.article', verbose_name='article'),
        ),
        migrations.AlterField(
            model_name='imagearticle',
            name='image_article',
            field=models.ImageField(help_text='article image', upload_to='image_article/%Y/%m/%d', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='imagearticle',
            name='img_alt',
            field=models.CharField(blank=True, help_text='text to be loaded in case of image loss', max_length=200, verbose_name='image alternative'),
        ),
        migrations.AlterField(
            model_name='textpage',
            name='content',
            field=ckeditor.fields.RichTextField(help_text='the content of the text page', verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='textpage',
            name='published',
            field=models.CharField(choices=[('d', 'draft'), ('p', 'published')], default='p', help_text='Published or draft', max_length=1, verbose_name='published'),
        ),
        migrations.AlterField(
            model_name='textpage',
            name='title',
            field=models.CharField(help_text='title of text page', max_length=150, unique=True, verbose_name='title'),
        ),
    ]
