# Generated by Django 3.2 on 2022-02-10 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0031_auto_20220210_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_preview',
            field=models.ImageField(help_text='article preview image', upload_to='article_preview/%Y/%m/%d', verbose_name='article preview'),
        ),
        migrations.AlterField(
            model_name='article',
            name='number_of_likes',
            field=models.PositiveIntegerField(default=0, help_text='number of article ratings', verbose_name='number of likes'),
        ),
    ]
