# Generated by Django 3.2 on 2022-02-10 18:15

import ckeditor.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0032_auto_20220210_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='content_ru',
            field=ckeditor.fields.RichTextField(help_text='the content of the article', null=True, verbose_name='content'),
        ),
        migrations.AddField(
            model_name='article',
            name='content_uk',
            field=ckeditor.fields.RichTextField(help_text='the content of the article', null=True, verbose_name='content'),
        ),
        migrations.AddField(
            model_name='article',
            name='img_alt_ru',
            field=models.CharField(blank=True, help_text='text to be loaded in case of image loss', max_length=200, null=True, verbose_name='image alternative'),
        ),
        migrations.AddField(
            model_name='article',
            name='img_alt_uk',
            field=models.CharField(blank=True, help_text='text to be loaded in case of image loss', max_length=200, null=True, verbose_name='image alternative'),
        ),
        migrations.AddField(
            model_name='article',
            name='short_description_ru',
            field=models.CharField(help_text='a short description about the article', max_length=350, null=True, verbose_name='short description'),
        ),
        migrations.AddField(
            model_name='article',
            name='short_description_uk',
            field=models.CharField(help_text='a short description about the article', max_length=350, null=True, verbose_name='short description'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_ru',
            field=models.CharField(help_text='title of article', max_length=200, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='title'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_uk',
            field=models.CharField(help_text='title of article', max_length=200, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='title'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ru',
            field=models.CharField(help_text='category name', max_length=100, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='name'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_uk',
            field=models.CharField(help_text='category name', max_length=100, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='name'),
        ),
        migrations.AddField(
            model_name='imagearticle',
            name='img_alt_ru',
            field=models.CharField(blank=True, help_text='text to be loaded in case of image loss', max_length=200, null=True, verbose_name='image alternative'),
        ),
        migrations.AddField(
            model_name='imagearticle',
            name='img_alt_uk',
            field=models.CharField(blank=True, help_text='text to be loaded in case of image loss', max_length=200, null=True, verbose_name='image alternative'),
        ),
        migrations.AddField(
            model_name='textpage',
            name='content_ru',
            field=ckeditor.fields.RichTextField(help_text='the content of the text page', null=True, verbose_name='content'),
        ),
        migrations.AddField(
            model_name='textpage',
            name='content_uk',
            field=ckeditor.fields.RichTextField(help_text='the content of the text page', null=True, verbose_name='content'),
        ),
        migrations.AddField(
            model_name='textpage',
            name='title_ru',
            field=models.CharField(help_text='title of text page', max_length=150, null=True, unique=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='textpage',
            name='title_uk',
            field=models.CharField(help_text='title of text page', max_length=150, null=True, unique=True, verbose_name='title'),
        ),
    ]
