# Generated by Django 3.2 on 2022-02-11 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0033_auto_20220210_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagearticle',
            name='image_article',
            field=models.ImageField(blank=True, help_text='article image', upload_to='image_article/%Y/%m/%d', verbose_name='image'),
        ),
    ]
